version: '3.7'
services:
  db:
    image: postgres:14-alpine

    env_file:
      - ./.env

    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: POSTGRES_DB

    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
  bot:
    build: .
    command: sh -c "python -m bot"
    env_file:
      - ./.env

    restart: always
    depends_on:
      - db

volumes:
  pgdata:
